### ISSUE TITLE
Installation on ubuntu 20.04

### ISSUE THREAD

**Issue by colindaven** [rrazaghi/modbamtools#12]
Hi,

I've tried to install on Ubuntu 1804 and 2004. 2004 was successful using

`pip3 --user install modbamtools`

However trying to use the tools likely picks up the python2.7 on the system and not the python3.8 which is also installed, and therefore can't find the lib listed below.

Any ideas how I temporarily change this eg with PYTHONPATH ? Or could it be another issue ?

Thanks
Colin

```
modbamtools


Traceback (most recent call last):
  File "/home/davenpor/.local/lib/python3.8/site-packages/PyPDF2/_utils.py", line 48, in <module>
    from typing import TypeAlias  # type: ignore[attr-defined]
ImportError: cannot import name 'TypeAlias' from 'typing' (/usr/lib/python3.8/typing.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/davenpor/.local/bin/modbamtools", line 5, in <module>
    from modbamtools.cli import cli
  File "/home/davenpor/.local/lib/python3.8/site-packages/modbamtools/cli.py", line 2, in <module>
    from modbamtools.modbamviz import *
  File "/home/davenpor/.local/lib/python3.8/site-packages/modbamtools/modbamviz.py", line 1, in <module>
    from modbamtools.utils import *
  File "/home/davenpor/.local/lib/python3.8/site-packages/modbamtools/utils.py", line 11, in <module>
    from PyPDF2 import PdfFileMerger
  File "/home/davenpor/.local/lib/python3.8/site-packages/PyPDF2/__init__.py", line 1, in <module>
    from ._merger import PdfFileMerger, PdfMerger
  File "/home/davenpor/.local/lib/python3.8/site-packages/PyPDF2/_merger.py", line 31, in <module>
    from ._page import PageObject
  File "/home/davenpor/.local/lib/python3.8/site-packages/PyPDF2/_page.py", line 47, in <module>
    from ._cmap import build_char_map, unknown_char_map
  File "/home/davenpor/.local/lib/python3.8/site-packages/PyPDF2/_cmap.py", line 7, in <module>
    from .generic import DecodedStreamObject, DictionaryObject, charset_encoding
  File "/home/davenpor/.local/lib/python3.8/site-packages/PyPDF2/generic.py", line 43, in <module>
    from ._utils import (
  File "/home/davenpor/.local/lib/python3.8/site-packages/PyPDF2/_utils.py", line 50, in <module>
    from typing_extensions import TypeAlias  # type: ignore[misc]
ImportError: cannot import name 'TypeAlias' from 'typing_extensions' (/usr/lib/python3/dist-packages/typing_extensions.py)
```

**Comment by rrazaghi** [comment]
Hi Colin!

I believe working in a clean python3.8 environment should resolve this! I'm trying to work on a conda release that hopefully will address all this. lmk if that doesn't work!

Thanks,
Roham
